config/routes.rb
MovieDB::Application.routes.draw do

  resources :searches
  resources :movies

end

app/models/categories.rb
class Categories < ActiveRecord::Base
  attr_accessible :title, :body
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end
  attr_accessible :title, :body, :year, :actors, :directors, :categories
end

app/models/search.rb
class Search < ActiveRecord::Base

  def search_movies
    movies = Movie.all

    movies = movies.where(["title LIKE ?", "%#{keywords}%"]) if keywords.present?
    movies = movies.where(["year LIKE ?", "%#{year}%"]) if year.present?
    movies = movies.where(["actors LIKE ?", "%#{actors}%"]) if keywords.present?
    movies = movies.where(["directors LIKE ?", "%#{directors}%"]) if directors.present?
    movies = movies.where(["categories LIKE ?", categories]) if categories.present?
    return movies
  end

  attr_accessible :actors, :categories, :directors, :keywords, :year
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.search(params[:search])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def new
    @search = Search.new
    @categories = Categories.uniq.pluck(:title)
  end

  def create
    @search = Search.create(params[:search])
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private
  def search_params
    params.require(:search).permit(:keywords, :year, :actors, :directors, :categories)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieDB</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="create">
  <div class="container">
    
    <%= form_for(@movie) do |f| %>
    <div class="field">
      <%= f.label "Film's title" %><br>
      <%= f.text_area :title %>
    </div>
    <div class="field">
      <%= f.label "Film's release year" %><br>
      <%= f.text_area :year %>
    </div>
    <div class="field">
      <%= f.label "Film's actors" %><br>
      <%= f.text_area :actors %>
    </div>
    <div class="field">
      <%= f.label "Film's directors" %><br>
      <%= f.text_area :directors %>
    </div>
    <div class="field">
      <%= f.label "Film's categories" %><br>
      <%= f.text_area :categories %>
    </div>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<%= form_tag movies_path, :method => 'get' do %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Search" %>
<% end %>

<p><%= link_to "Advanced Search", new_search_path %> <b>Only work with Rails 4</b></p>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.title %></td>
    <td><%= movie.year %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<div>
<h1><%= @movie.title =%></h1>
<h1><%= @movie.year =%></h1>
<h2><u>Category</u></h2>
<div class="tag">
  <h4 class="tag-name"><%= @movie.categories %></h4>
</div>
<h1>Cast</h1>
<h2><u>Director(s) :</u></h2>
<div class="director">
  <h4 class="director-name"><%= @movie.directors %></h4>
</div>
<h2><u>Actors :</u></h2>
<div class="actor">
  <h4 class="actor-name"><%= @movie.actors %></h4>
</div>
</div>

<%= link_to 'Back', movies_path %>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_for @search, html: {class: "pure-form"} do |s| %>

<div class="field">
  <%= s.label :keywords %><br />
  <%= s.text_field :keywords %>
</div>

<div class="field">
    <%= s.label :year %><br />
    <%= s.text_field :year %>
</div>

<div class="field">
    <%= s.label :actors %><br />
    <%= s.text_field :actors %>
</div>

<div class="field">
    <%= s.label :directors %><br />
    <%= s.text_field :directors %>
</div>

<div class="field">
    <%= s.label :categories %><br />
    <%= s.select :categories, options_for_select(@categories), :include_blank => true %>
</div>

<div class"actions"><%= s.submit "Search", class: "pure-button pure-button-primary" %></div>

<% end %>

<p><%= link_to 'Back', movies_path %></p>

app/views/searches/show.html.erb
<h1>Search Result</h1>
<p><%= link_to "Back", new_search_path %></p>

<% if @search.search_movies.empty? %>
<p>No Movies Found</p>
<% else %>
<% @search.search_movies.each do |c| %>
<br>

<div class="div">
  <h1><%= c.title %></h1>
  <p>Year : <%= c.year %></p>
  <h2>Cast</h2>
  <p>Director : <%= c.directors %></p>
  <p>Actors : <%= c.actors %></p>
  <p>Categories : <%= c.categories %></p>
</div>

<% end %>

<% end %>

    